### ISSUE TITLE
Specify content-type in response

### ISSUE THREAD

**Issue by jamescarr** [Marak/webservice.js#11]
Would be nice to see some automatic content-type creation in responses. For example if the response is json then send content-type:'application/json'. 

Some potential client application libraries (such as apache CXF) automatically construct objects based on this.

**Comment by Marak** [comment]
Agreed, wanna do up a patch? Library needs some love :-(

**Comment by jamescarr** [comment]
LOL... I just may. I wanted to use this to publish a quick and dirty REST service to plug into a demo app but the content-type missing was a gotcha. :)
