### ISSUE TITLE
Disable access from remote domains per module/method

### ISSUE THREAD

**Issue by justmoon** [Marak/webservice.js#13]
It's convenient to use session authentication inside webservice methods, however this opens up some obvious XSS vulnerabilities.

One solution would be to add a way to disable remote access per module or method. This would disable JSONP and any future remote access methods webservice.js may implement (Flash cross domain policy, WebSockets, etc.)

**Comment by Marak** [comment]
What exactly do you want to do here?

Do you want to add an API option so any requests originating from a non-friendly domain are rejected? Perhaps add a "white-list" domain option when starting up a webservice?

I think you are on to something here. It would be great if you could add a few tests or even just pseudo code to illustrate how you'd like to see the API work.

**Comment by justmoon** [comment]
After thinking about it some more, I think it would be ideal if webservice.js simply passed a flag whether the call came in through a channel (like HTTP POST) that proves it came from the local domain.

It'll become clearer once I give you an example. So here goes:

Let's say I have a website acme.com.

Now usually, if it's an AJAX driven website I'll have some internal URL I call to - for instance - post comments. Let's say that URL is http://acme.com/ajax/postComment

Obviously I do not want other websites to call this URL without my users' knowledge. That's why if a script on evildoers.com tries a $.post('http://acme.com/ajax/postComment'), the browser will step in and won't allow it. And of course I would never add JSONP support to this handler because it's GOOD that only my site can call it.

Ok. Now:

I also have some external APIs that other people can use. For example I may have an API that let's other people retrieve all comments for a certain item: http://api.acme.com/comment/list

There may also be an API for posting comments even, which depends on some OAuth type authorization ("Would you like to allow evildoers.com to post comments for you?")
http://api.acme.com/comment/post

Now what I've noticed that my code for "acme.com/ajax/postComment" is exactly the same as my code for "api.acme.com/comment/post". Except (!) for the authorization part.

ajax/postComment will look at the session cookie, authenticate the user and post the comment
api/comment/post will look at the OAuth signature/authorization and post the comment

What I would love to do is have a _single_ API for internal and external calls. So I'd have a module like so:

```
this.title = "Do some CRUD with comments";
this.name = "comments module";
this.version = "0.1.0";
this.endpoint = "http://localhost:8080";

exports.post = function (options, callback) {
    if (this.isSameOrigin) {
        // Require cookie-type authentication, otherwise fail
    } else {
        // Require OAuth-type authentication, otherwise fail
    }

    // Post the comment
};
```

And I'd put it on http://acme.com/api/comment/ and I'd POST to it internally with my AJAX stuff and other people can JSONP it and - using OAuth - even run priviledged methods like "post".

**Comment by Marak** [comment]
_After thinking about it some more, I think it would be ideal if webservice.js simply passed a flag whether the call came in through a channel (like HTTP POST) that proves it came from the local domain._

How do you know what the "local domain" is? Node listens on a port and ip address, a node httpServer is not bound to any specific domain. I'm not sure how to do this without using a white-list.

**Comment by justmoon** [comment]
You don't need to know what the local domain is. If the request comes in as a HTTP POST, then it must have been a same origin request.

Right now, you could just use this:

```
exports.post = function (options, callback) {
    if (this.request.method === 'POST') {
        // Require cookie-type authentication, otherwise fail
    } else {
        // Require OAuth-type authentication, otherwise fail
    }

    // Post the comment
};
```

Only thing I'm not sure about is whether this is future proof. So I would put the `this.request.method === 'POST'` part in webservice.js and in the handler use something like "isSameOrigin". If webservice.js does anything in the future that may break same origin policy (such as add a crossdomain,xml file that allows POST requests) you could add an additional condition (such as setting isSameOrigin to false for all requests coming from Flash.)
