### ISSUE TITLE
Documentation: Add example for multiple modules

### ISSUE THREAD

**Issue by justmoon** [Marak/webservice.js#14]
I noticed old versions of the documentation show the syntax for exposing multiple modules. I assume most people will want to expose multiple modules. I also assume that this change was made to allow for more flexibility instead of less. So this is probably a matter of just adding an example to the README for how to do this again.

**Comment by Marak** [comment]
I changed the API up from before. The idea was the new way of exposing multiple modules is to include one module and inside that module you require other modules as top level exports. 

I'm not sure if the new API is the best choice, it might make sense to go back to the old way.

**Comment by justmoon** [comment]
It really doesn't matter I think, either API is fine. Isn't the new one even backwards compatible? As in: If I pass an object like {fs: fs, demo: demoModule} wouldn't it correctly create the webservices at the "fs" and "demo" paths? If that works, then I'd say leave it as it is, just add an example to the docs.

One followup question:
Is it possible to use webservice.js as a middleware in Express? For example let's say I have a website example.com and I want my webservices like so:

http://example.com/api/[module]/[method]/...

Could I just

```
app.get('/api', webservice.createHandler(...));
```

?
