### ISSUE TITLE
Installing from npm has missing dependencies

### ISSUE THREAD

**Issue by coen-hyde** [Marak/webservice.js#19]
It appears as though webservice is missing both eyes and resourcer.

**Comment by Marak** [comment]
Hrmm, that's not right. Let me see what I can do.

**Comment by Marak** [comment]
Okay, I'm not sure how that slipped by, must have changed the dep awhile back since I'm using a Resourcer fork, not the main branch.

All deps should be vendor now and package should install properly from npm. Could you confirm? Thanks!

**Comment by Marak** [comment]
Oops, I pushed a borked package.json. Should be OK now. Sorry.

**Comment by coen-hyde** [comment]
Hi Marak,

All fixed now. Thanks for the quick response!

Coen

**Comment by Marak** [comment]
Glad to be of help. Please let me know if you have any additional issues or questions. I'm not really using this library anywhere at the moment, so I'm open to suggestions.
