### ISSUE TITLE
Auth support

### ISSUE THREAD

**Issue by outaTiME** [Marak/webservice.js#24]
Will be interesting to perform some authentication mechanism to protect methods.

**Comment by Marak** [comment]
Journey does have a filter method for routes, doing basic auth with a hard-coded admin user would be pretty trivial I think.

**Comment by outaTiME** [comment]
yup, but your lib is awesome ... journey requires a lot of code to create pretty api =(

**Comment by Marak** [comment]
Webservice.js uses Journey as it's internal router.

See: 

https://github.com/Marak/webservice.js/blob/master/lib/createHandler.js#L8
https://github.com/Marak/webservice.js/blob/master/lib/createRouter.js#L23

I will take a patch that adds basicAuth filtering. You can add a filter property on line 23 that points to a basicAuth method like:

``` javascript

basicAuth = function (request, body, callback) {
  function notAuthorized(message) {
    callback(new journey.NotAuthorized(message));
  }

  var realm = "Authorization Required",
      authorization = request.headers.authorization,
      parts,
      scheme,
      decoded,
      credentials;

  if (!authorization) {
    return notAuthorized("Authorization header is required.");
  }

  // Parse the authorization header for `(Scheme)\s{1}(username)\:(password)`
  parts         = authorization.split(" ");                    // Basic salkd787&u34n=
  scheme        = parts[0];                                     // Basic
  decoded       = base64.decode(parts[1]);             // admin:password || null
  credentials   = decoded && decoded.split(":");     // ['admin', 'password'] || null

  if (scheme !== "Basic") {
    return notAuthorized("Authorization scheme must be 'Basic'");
  }
  else if ( typeof credentials[0] !== 'string' || typeof credentials[1] !== 'string') {
    return notAuthorized("Both username and password are required");
  }

  if(credentials[0] === "admin" && credentials[1] === "admin") { 
    // authorized
    callback(null);
  } else {
    return notAuthorized("Bad creds!'");
  }


```

This should be almost all the code you need...good luck friend and may the force of node be with you.

**Comment by outaTiME** [comment]
mark, this is excellent ... I'll be testing tonight ... 

thanks for all your time and good vibes !!!

**Comment by outaTiME** [comment]
marak, sorry .... bad typo ....
