### ISSUE TITLE
Broken on node 0.6

### ISSUE THREAD

**Issue by dortzur** [Marak/webservice.js#35]
can't use this on node 0.6
require.paths breaks everything.
when are planning to update?

**Comment by dhendo** [comment]
Try this: https://github.com/Marak/webservice.js/issues/34#issuecomment-3159349

**Comment by dortzur** [comment]
Doesn't work, i think it's because marak dist your fork.
Anyway i'm using express + connect to expose a RESTful API.
seems a shame to let this project die though

**Comment by Marak** [comment]
Who said anything about dying?

It looks like there is a fork with 0.6.x support. If you found a different solution, cool. 

I'm thinking there will be a new version of webservice.js that uses the Flatiron stack ( Director and Revalidator )

I will be commenting more on @dhendo fork.

**Comment by baio** [comment]
@dhendo Hi! I've installed your fork via npm but it still doesn't work. First of all it I got error - eyes module not found in createClient and when I commented this next error:

Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:376:11)
    at Object.<anonymous> (/home/baio/node_modules/webservice/node_modules/journey/lib/journey.js:3:8)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/home/baio/node_modules/webservice/lib/createRouter.js:1:127)
    at Module._compile (module.js:432:26)

Process finished with exit code 1

**Comment by dhendo** [comment]
Are you sure it is using my fork, and that you don't have the original repo in the node_modules folder or something?

The above errors sound like the old code is being used.

If not, I'll check it out tomorrow.

**Comment by baio** [comment]
@dhendo Hi, to insatll I use - npm install git://github.com/dhendo/webservice.js.git before that I removed all webservice modules installed previously, its for shure!

**Comment by dhendo** [comment]
I've updated the package file - now looks to work OK for me with the following:

https://gist.github.com/2168516

**Comment by baio** [comment]
thanks will try it !

**Comment by baio** [comment]
thanks it works!
